language: go
go:
    - 1.2
    - tip
install:
    - go get code.google.com/p/go.tools/cmd/cover
    - go get code.google.com/p/go.tools/cmd/vet
    - go get -a -race -v ./...
    - go install -a -race std
script:
    - go vet ./...
    - go test -race -v -covermode=atomic ./...
